class Planet {
  final String name;
  final String image;
  final String model3D;
  final String title;
  final String about;
  final int distanceFromSun;
  final double lengthOfDay;
  final double orbitalPeriod;
  final double radius;
  final String mass;
  final double gravity;
  final String surfaceArea;

  Planet({
    required this.name,
    required this.image,
    required this.model3D,
    required this.title,
    required this.about,
    required this.distanceFromSun,
    required this.lengthOfDay,
    required this.orbitalPeriod,
    required this.radius,
    required this.mass,
    required this.gravity,
    required this.surfaceArea,
  });
}

class SolarSystemData {
  static final List<Planet> planets = [
    Planet(
      name: "Sun",
      image: "sun.png",
      model3D: "sun.glb",
      title: "The Sun: Our Solar System's Star",
      about: "The Sun is the heart of our solar system, a massive star that provides the energy for life on Earth.",
      distanceFromSun: 0,
      lengthOfDay: 0.0,
      orbitalPeriod: 0.0,
      radius: 695700.0,
      mass: "1.989 × 10³⁰",
      gravity: 274.0,
      surfaceArea: "6.09 × 10¹²",
    ),
    Planet(
      name: "Mercury",
      image: "mercury.png",
      model3D: "mercury.glb",
      title: "Mercury: The Closest Planet",
      about: "Mercury is the smallest planet in our solar system and the closest to the Sun.",
      distanceFromSun: 57909227,
      lengthOfDay: 1407.6,
      orbitalPeriod: 0.24,
      radius: 2439.7,
      mass: "3.301 × 10²³",
      gravity: 3.7,
      surfaceArea: "7.48 × 10⁷",
    ),
    Planet(
      name: "Venus",
      image: "venus.png",
      model3D: "venus.glb",
      title: "Venus: Earth's Toxic Twin",
      about: "Venus is often referred to as Earth's twin due to its similar size, though its atmosphere is toxic.",
      distanceFromSun: 108209072,
      lengthOfDay: 5832.2,
      orbitalPeriod: 0.62,
      radius: 6051.8,
      mass: "4.867 × 10²⁴",
      gravity: 8.87,
      surfaceArea: "4.60 × 10⁸",
    ),
    Planet(
      name: "Earth",
      image: "earth.png",
      model3D: "earth.glb",
      title: "Earth: Our Blue Marble",
      about: "Earth is the only known planet in the universe to harbor life.",
      distanceFromSun: 149598026,
      lengthOfDay: 23.93,
      orbitalPeriod: 1.0,
      radius: 6371.0,
      mass: "5.972 × 10²⁴",
      gravity: 9.81,
      surfaceArea: "5.10 × 10⁸",
    ),
    Planet(
      name: "Mars",
      image: "mars.png",
      model3D: "mars.glb",
      title: "Mars: The Red Planet",
      about: "Mars, often called the Red Planet due to its reddish appearance, has been a focus of exploration.",
      distanceFromSun: 227943824,
      lengthOfDay: 24.62,
      orbitalPeriod: 1.88,
      radius: 3389.5,
      mass: "6.39 × 10²³",
      gravity: 3.71,
      surfaceArea: "1.45 × 10⁸",
    ),
    Planet(
      name: "Jupiter",
      image: "jupiter.png",
      model3D: "jupiter.glb",
      title: "Jupiter: The Gas Giant",
      about: "Jupiter is the largest planet in our solar system, known for its Great Red Spot and many moons.",
      distanceFromSun: 778340821,
      lengthOfDay: 9.93,
      orbitalPeriod: 11.86,
      radius: 69911.0,
      mass: "1.898 × 10²⁷",
      gravity: 24.79,
      surfaceArea: "6.14 × 10⁹",
    ),
    Planet(
      name: "Saturn",
      image: "saturn.png",
      model3D: "saturn.glb",
      title: "Saturn: The Ringed Planet",
      about: "Saturn is famous for its stunning ring system, made of ice and rock particles.",
      distanceFromSun: 1426666422,
      lengthOfDay: 10.7,
      orbitalPeriod: 29.46,
      radius: 58232.0,
      mass: "5.683 × 10²⁶",
      gravity: 10.44,
      surfaceArea: "4.27 × 10⁹",
    ),
    Planet(
      name: "Uranus",
      image: "uranus.png",
      model3D: "uranus.glb",
      title: "Uranus: The Ice Giant",
      about: "Uranus has a unique rotation axis and is known for its pale blue color due to methane in its atmosphere.",
      distanceFromSun: 2870658186,
      lengthOfDay: 17.24,
      orbitalPeriod: 84.01,
      radius: 25362.0,
      mass: "8.681 × 10²⁵",
      gravity: 8.87,
      surfaceArea: "8.08 × 10⁸",
    ),
    Planet(
      name: "Neptune",
      image: "neptune.png",
      model3D: "neptune.glb",
      title: "Neptune: The Windy Planet",
      about: "Neptune is known for its deep blue color and the fastest winds in the solar system.",
      distanceFromSun: 4498396441,
      lengthOfDay: 16.11,
      orbitalPeriod: 164.79,
      radius: 24622.0,
      mass: "1.024 × 10²⁶",
      gravity: 11.15,
      surfaceArea: "7.64 × 10⁸",
    ),
    Planet(
      name: "Pluto",
      image: "pluto.png",
      model3D: "pluto.glb",
      title: "Pluto: The Dwarf Planet",
      about: "Pluto, once considered the ninth planet, is now classified as a dwarf planet in the Kuiper belt.",
      distanceFromSun: 5906440628,
      lengthOfDay: 153.29,
      orbitalPeriod: 248.0,
      radius: 1188.3,
      mass: "1.309 × 10²²",
      gravity: 0.62,
      surfaceArea: "1.77 × 10⁷",
    ),
  ];
}
